-- ============================================================================
-- Script: 01_creacion_rol_y_asignacion_login.sql
-- Proyecto: Conexion Carga - Login administrativo web
-- Motor: PostgreSQL
-- Alcance:
--   1) Crear tabla conexion_carga.rol
--   2) Crear columna users.rol_id
--   3) Crear rol Administrador
--   4) Relacionar users.rol_id -> rol.id
--   5) Asignar Administrador a usuarios permitidos (lista controlada)
--
-- IMPORTANTE:
-- - Script idempotente.
-- - NO se ejecuta automaticamente desde la app.
-- - Revisar y ajustar lista de correos administradores antes de ejecutar.
-- ============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS conexion_carga;

CREATE TABLE IF NOT EXISTS conexion_carga.rol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

INSERT INTO conexion_carga.rol (nombre, descripcion, activo)
VALUES ('Administrador', 'Rol administrativo para panel web', TRUE)
ON CONFLICT (nombre)
DO UPDATE
SET
    descripcion = EXCLUDED.descripcion,
    activo = EXCLUDED.activo;

ALTER TABLE conexion_carga.users
ADD COLUMN IF NOT EXISTS rol_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'users_rol_id_fkey'
    ) THEN
        ALTER TABLE conexion_carga.users
        ADD CONSTRAINT users_rol_id_fkey
        FOREIGN KEY (rol_id)
        REFERENCES conexion_carga.rol (id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_users_rol_id
    ON conexion_carga.users (rol_id);

-- Asignacion segura y controlada de rol Administrador.
-- Ajustar esta lista antes de ejecutar en produccion.
WITH rol_admin AS (
    SELECT id
    FROM conexion_carga.rol
    WHERE LOWER(nombre) = LOWER('Administrador')
    LIMIT 1
)
UPDATE conexion_carga.users u
SET rol_id = ra.id
FROM rol_admin ra
WHERE u.rol_id IS NULL
  AND LOWER(u.email) IN (
      LOWER('admin@conexioncarga.com'),
      LOWER('daniloramirez0818@gmail.com'),
      LOWER('ddgaviriaz@unal.edu.co')
  );

COMMIT;

-- Consultas de verificacion manual (no modifican datos):
-- SELECT id, nombre, activo FROM conexion_carga.rol ORDER BY id;
-- SELECT email, rol_id FROM conexion_carga.users ORDER BY created_at DESC LIMIT 20;
-- SELECT u.email, r.nombre AS rol
-- FROM conexion_carga.users u
-- LEFT JOIN conexion_carga.rol r ON r.id = u.rol_id
-- ORDER BY u.created_at DESC LIMIT 20;
