-- ============================================================================
-- Script: 02_eliminacion_controlada_viajes.sql
-- Proyecto: Conexion Carga - Administracion de Viajes (eliminacion con trazabilidad)
-- Motor: PostgreSQL
-- Alcance:
--   1) Crear tabla conexion_carga.causales_eliminacion
--   2) Crear tabla conexion_carga.carga_eliminada (historico / auditoria)
--   3) Crear indices de consulta
--   4) Sembrar causales iniciales
--
-- IMPORTANTE:
-- - Script idempotente.
-- - Puede ejecutarse en dev para pruebas.
-- - En produccion debe revisarse y ejecutarse de forma controlada.
-- ============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS conexion_carga;

CREATE TABLE IF NOT EXISTS conexion_carga.causales_eliminacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(160) NOT NULL UNIQUE,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conexion_carga.carga_eliminada (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    carga_id UUID NOT NULL,
    causal_id BIGINT NOT NULL,
    observacion TEXT,
    eliminado_por UUID NULL,
    eliminado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    snapshot_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT carga_eliminada_carga_fkey
        FOREIGN KEY (carga_id)
        REFERENCES conexion_carga.carga (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT carga_eliminada_causal_fkey
        FOREIGN KEY (causal_id)
        REFERENCES conexion_carga.causales_eliminacion (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT carga_eliminada_usuario_fkey
        FOREIGN KEY (eliminado_por)
        REFERENCES conexion_carga.users (id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_carga_eliminada_carga_id
    ON conexion_carga.carga_eliminada (carga_id);

CREATE INDEX IF NOT EXISTS idx_carga_eliminada_eliminado_en
    ON conexion_carga.carga_eliminada (eliminado_en DESC);

CREATE INDEX IF NOT EXISTS idx_carga_eliminada_causal_id
    ON conexion_carga.carga_eliminada (causal_id);

CREATE INDEX IF NOT EXISTS idx_carga_eliminada_eliminado_por
    ON conexion_carga.carga_eliminada (eliminado_por);

INSERT INTO conexion_carga.causales_eliminacion (nombre, descripcion, activo)
VALUES
    ('Administrador solicitó eliminación', 'Retiro administrativo controlado', TRUE),
    ('Información incorrecta', 'Datos inconsistentes o incompletos', TRUE),
    ('Viaje duplicado', 'El viaje ya habia sido publicado previamente', TRUE),
    ('Fraude / sospecha', 'Posible comportamiento fraudulento o riesgoso', TRUE),
    ('Otro (Observación libre)', 'Motivo no contemplado en causales predefinidas', TRUE)
ON CONFLICT (nombre)
DO UPDATE
SET
    descripcion = EXCLUDED.descripcion,
    activo = EXCLUDED.activo,
    updated_at = NOW();

UPDATE conexion_carga.causales_eliminacion
SET
    nombre = 'Otro (Observación libre)',
    descripcion = 'Motivo no contemplado en causales predefinidas',
    updated_at = NOW()
WHERE LOWER(nombre) = LOWER('Otro')
  AND NOT EXISTS (
      SELECT 1
      FROM conexion_carga.causales_eliminacion
      WHERE LOWER(nombre) = LOWER('Otro (Observación libre)')
  );

UPDATE conexion_carga.causales_eliminacion
SET
    activo = FALSE,
    updated_at = NOW()
WHERE LOWER(nombre) = LOWER('Otro')
  AND EXISTS (
      SELECT 1
      FROM conexion_carga.causales_eliminacion
      WHERE LOWER(nombre) = LOWER('Otro (Observación libre)')
  );

UPDATE conexion_carga.causales_eliminacion
SET
    nombre = 'Administrador solicitó eliminación',
    descripcion = 'Retiro administrativo controlado',
    updated_at = NOW()
WHERE LOWER(nombre) = LOWER('Usuario solicitó eliminación')
  AND NOT EXISTS (
      SELECT 1
      FROM conexion_carga.causales_eliminacion
      WHERE LOWER(nombre) = LOWER('Administrador solicitó eliminación')
  );

UPDATE conexion_carga.causales_eliminacion
SET
    activo = FALSE,
    updated_at = NOW()
WHERE LOWER(nombre) = LOWER('Usuario solicitó eliminación')
  AND EXISTS (
      SELECT 1
      FROM conexion_carga.causales_eliminacion
      WHERE LOWER(nombre) = LOWER('Administrador solicitó eliminación')
  );

COMMIT;

-- Consultas de verificacion manual:
-- SELECT id, nombre, activo FROM conexion_carga.causales_eliminacion ORDER BY id;
-- SELECT id, carga_id, causal_id, eliminado_por, eliminado_en
-- FROM conexion_carga.carga_eliminada
-- ORDER BY eliminado_en DESC
-- LIMIT 20;
